### ISSUE TITLE
Precompiled deb package does not install on Raspberry Pi

### ISSUE THREAD

**Issue by riban-bw** [rerdavies/ToobAmp#46]
I downloaded the [precompiled package for Raspberry Pi](https://github.com/rerdavies/ToobAmp/releases/download/v1.0.17/toobamp_1.0.17_arm64.deb) and tried to install but get the error:

```
The following packages have unmet dependencies:
 toobamp : Depends: libflac++6v5 (>= 1.3.1) but it is not installable
E: Unable to correct problems, you have held broken packages.
```

I am running Debian 12 (Bookworm) on a Raspberry Pi 4 within a [Zynthian](https://zynthian.org/). Debian package search shows a similarly named package, "libflac++10".

**Comment by rerdavies** [comment]
Please try:

https://github.com/rerdavies/ToobAmp/releases/download/v1.1.31/toobamp_1.1.31_arm64.deb

That should fix the problem.
