### ISSUE TITLE
Where can I download toobamp_1.1.43_arm64.deb??

### ISSUE THREAD

**Issue by maarthome** [rerdavies/ToobAmp#49]
Hi Robin,

Where can I download toobamp_1.1.43_arm64.deb??

Thanks,
Maarten

**Comment by rerdavies** [comment]
I, umm.. cleaned up some of the obsolete downloads.

Is there some reason why the most recent release isn't good for you?

**Comment by maarthome** [comment]
Hi Robin...

Not good enough?
I would like to benefit from the latest performance improvement:

quote: "Modest performance improvements for TooB Neural Amp Modeler (about 8% faster)."

I think 8% is a lot....

Cheers,

Maarten
