### ISSUE TITLE
Where can I download ToobAmp VERSION 1.1.49?

### ISSUE THREAD

**Issue by maarthome** [rerdavies/ToobAmp#50]
Hi Robin,

Where can I download ToobAmp VERSION 1.1.49?

Cheers,

Maarten

**Comment by rerdavies** [comment]
Sorry. 1.1.49 was an experimental release, so I removed it from the  list of available downloads while doing a little housekeeping. I'm afraid I don't have a copy of it on my dev machine either. Maybe that wasn't such a good idea. :-(

**Comment by rerdavies** [comment]
As best I can recall, v1.1.49 was an experimental release whose sole purpose was to field-test a fix for you that was later rolled into v1.1.51.

**Comment by maarthome** [comment]
Hi Robin,

I think we misunderstand eachother...?
This is waht I am refering to with Toobamp 1.1.49:

![{75DCC4C2-5394-4F45-8058-D883BAD2B5D4}](https://github.com/user-attachments/assets/2eb3a402-9ffe-400d-a64d-5720d28caeb7)

Cheers,
Maarten

**Comment by rerdavies** [comment]
Oh! We are misunderstanding each other. Lol

I can cook up a build for you. Be advised though, that PiPedal and ToobAmp
installs conflict with each other. Pipedal always contains the latest
ToobAmp plugins. So if you are using PiPedal, you don't want or need a
ToobAmp package.

Were you looking for an x86 or an arm64 build? If the former, I'm afraid
you'll have to build it yourself as my x86 Linux box has died an untimely
death.

That being said, I'd be happy to cook up an arm64 build if that's what
you're looking for.

Let me know.

**Comment by maarthome** [comment]
Hi robin,

I really appreciate your offer! :-)
But I do not want to take to much effort from you.
What I did now is install the  available version and copy the content of the pipedal Toob directory. It seems to work... :-)

I am using your plugins in the Zynthian application (MOD-UI implementation) (take a look at it is a wondeful project too: https://wiki.zynthian.org/index.php/Zynthian_Wiki_Home)

For 'only' guitar with voice however I use Pipedal because of user interface, stability, and user ease of use )

Thanks again for your energy and helpfullness,
Maarten
